### ISSUE TITLE
A config field with both 'required' and 'default' set is considered invalid if a value isn't supplied

### ISSUE THREAD

**Issue by aphistic** [efritz/nacelle#1]
I have a config where I have the field both required and provide a default value.  This is a pretty weird case because normally not a reason to have both on the same field but I'm doing development on a new app and I want to be able to supply a default value during development but remove it before the final release (or even once I have some more of the app structure done).  I want to keep the field required, though, so I don't forget to make it required once the default is removed.

**Comment by efritz** [comment]
No shortcuts in dev, Erik!

**Comment by aphistic** [comment]
:(

**Comment by efritz** [comment]
Just saying - you want to supply a default value because you don't want an environment variable, but you also don't want to remove the required tag because you'll forget -- but you have to remember to remove the default value anyway, so that line of code is changing either way after you're done with your initial dev POC.
